vich_uploader:
    db_driver: orm

    mappings:
        cover_pictures:
            uri_prefix: /images/cover_pictures
            upload_destination: "%kernel.project_dir%/public/images/cover_pictures"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
