# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mtn_momo.base_url: "%env(MTN_MOMO_BASE_URL)%"
    mtn_momo.subscription_key: "%env(MTN_MOMO_SUBSCRIPTION_KEY)%"
    mtn_momo.user_id: "%env(MTN_MOMO_USER_ID)%"
    mtn_momo.api_key: "%env(MTN_MOMO_API_KEY)%"
    mtn_momo.environment: "%env(MTN_MOMO_ENVIRONMENT)%"
    mtn_momo.currency: "%env(MTN_MOMO_CURRENCY)%"

    airtel_money.base_url: "%env(AIRTEL_MONEY_BASE_URL)%"
    airtel_money.client_id: "%env(AIRTEL_MONEY_CLIENT_ID)%"
    airtel_money.client_secret: "%env(AIRTEL_MONEY_CLIENT_SECRET)%"
    airtel_money.country: "%env(AIRTEL_MONEY_COUNTRY)%"
    airtel_money.currency: "%env(AIRTEL_MONEY_CURRENCY)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
